server:
  port: 8080
spring:
  application:
    name: Project Reggie
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      url: jdbc:mysql://localhost:3306/reggie?serverTimezone=UTC
      username: root
      password: root
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
#      id-type: auto
      id-type: assign_id
  type-aliases-package: com.mk.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
#      id-type: uuid
reggie:
  basePath: D:\Java\SSM\UploadFIle\Reggie\
